# Generated by Django 4.0.4 on 2022-05-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celtic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
    ]
