# Generated by Django 4.0.4 on 2022-05-27 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celtic',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='celtic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celtic',
            name='height_in_inches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='celtic',
            name='number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='celtic',
            name='salary_in_dollars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='celtic',
            name='weight_in_lbs',
            field=models.IntegerField(default=0),
        ),
    ]
