# Generated by Django 4.0.4 on 2022-05-31 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_celtic_age_celtic_created_at_celtic_height_in_inches_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Celtic',
            new_name='Player',
        ),
    ]
