# Generated by Django 4.0.4 on 2022-06-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_celtic_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
        migrations.RemoveField(
            model_name='player',
            name='college',
        ),
        migrations.RemoveField(
            model_name='player',
            name='height_in_inches',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.RemoveField(
            model_name='player',
            name='salary_in_dollars',
        ),
        migrations.RemoveField(
            model_name='player',
            name='weight_in_lbs',
        ),
    ]
