# Generated by Django 4.0.4 on 2022-06-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='former_teams',
            field=models.ManyToManyField(to='main_app.team'),
        ),
    ]
