# Generated by Django 4.0.4 on 2022-06-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_player_former_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='former_teams',
            field=models.ManyToManyField(blank=True, related_name='former_players', to='main_app.team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.CharField(default='0', max_length=3),
        ),
    ]
